#!/usr/bin/env python

import sys
import os
import errno


def files(folder):
    files_and_folders = os.listdir(folder)
    return {filename for filename in files_and_folders if
            os.path.isfile(os.path.join(folder, filename))}

try:
    files1 = files(sys.argv[1])
    files2 = files(sys.argv[2])
except OSError as e:
    if e.errno == errno.ENOENT:
        print("One or both of the supplied folder names was not found")
        sys.exit(1)
    else:
        raise e
except IndexError:
    print("You must supply the paths to two folders to compare")
    sys.exit(1)
else:
    intersection = files1.intersection(files2)
    if len(intersection):
        for member in intersection:
            print(member)
    else:
        print("-- Empty intersection --")
