#!/usr/bin/env python

import sys
import os


def files(folder):
    files_and_folders = os.listdir(folder)
    return {filename for filename in files_and_folders if
            os.path.isfile(os.path.join(folder, filename))}

try:
    files1 = files(sys.argv[1])
    files2 = files(sys.argv[2])
except FileNotFoundError:
    print("One or both of the supplied folder names was not found")
    sys.exit(1)
except IndexError:
    print("You must supply the paths to two folders to compare")
    sys.exit(1)
else:
    intersection = set(files1) & set(files2)
    if len(intersection):
        for member in intersection:
            print(member)
    else:
        print("-- Empty intersection --")
