#!/usr/bin/env python

import sys
import os

try:
    dir1 = os.listdir(sys.argv[1])
    dir2 = os.listdir(sys.argv[2])
except FileNotFoundError:
    print("One or both of the supplied folder names was not found")
    sys.exit(1)
except IndexError:
    print("You must supply the paths to two folders to compare")
    sys.exit(1)
else:
    files1 = [member for member in dir1 if
              os.path.isfile(os.path.join(sys.argv[1], member))]
    files2 = [member for member in dir2 if
              os.path.isfile(os.path.join(sys.argv[2], member))]
    intersection = set(files1) & set(files2)
    if len(intersection):
        for member in intersection:
            print(member)
    else:
        print("-- Empty intersection --")
